version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.11-browsers
    steps:
      - checkout
      - run: cp .env.testing .env
      - run: sudo apt-get install -y libsqlite3-dev
      - run: composer install -n --ignore-platform-reqs
      - run: vendor/bin/phpunit

      - run:
         name: Start Chrome Driver
         command: ./vendor/laravel/dusk/bin/chromedriver-linux
         background: true

      - run:
         name: Run Laravel Server
         command: php artisan serve --port=9000
         background: true

      - run:
         name: Run Laravel Dusk Tests
         command: php artisan dusk